### ISSUE TITLE
Fixes broken CircleCI ubuntu 16 image

### ISSUE THREAD

**Issue by Pi-George** [criswell/test-circle#4]
Hey I came from https://discuss.circleci.com/t/circlecis-ubuntu-1604-docker-image-seems-to-be-having-gpg-key-problems/35891

The reason no one else mentioned it is because the community forums for CircleCI are horrible to login to due to their two factor authentication so most people give up trying and don't use the site. 

Anyway here's the fix I'm using, I hope it helps you:

 ```
  - run:
          name: Fix GPG key issues
          command: |
            sudo apt-get remove heroku
            sudo add-apt-repository "deb https://cli-assets.heroku.com/branches/stable/apt ./"
            curl -fL https://cli-assets.heroku.com/apt/release.key | sudo apt-key add -
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo apt update 2>&1 1>/dev/null | sed -ne 's/.*NO_PUBKEY //p' | while read key; do
              if ! [[ ${keys[*]} =~ "$key" ]]; then
                sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys "$key"
                keys+=("$key")
              fi
            done
```

Putting that in your circleci config.yml at the top of your job should work.

**Comment by criswell** [comment]
Thanks.

Yeah I actually also submitted a ticket to Circle and got some support on this. They've updated their images to resolve this issue (see the most recent change against master for the fix).

We knew we could just do tomfoolery with the keys and removing repos, but we shouldn't have to... this is Circle's official image :-) So I filed a ticket.
